/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include"i2c.h"
#include"uart.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	UartInit(9600);
	UartPuts("Hello STM32!\r\n");
	UartPuts("Hello DESD!\r\n");
	UartPuts("God Bless You!\r\n");


	int8_t reg,addr=0x68;
	uint8_t data[14];
	int16_t accel_x,accel_y,accel_z,temp_raw,gyro_x,gyro_y,gyro_z;
	int32_t temp_mc,temp_c;

	char str[128];
	I2CInit();
	reg=0x75;//WHO_AM_I register
	I2CWrite(addr, reg);
	data[0]=I2CRead(addr);
	sprintf(str,"WHO_AM_I = 0x%02X\r\n",data[0]);
	UartPuts(str);

	reg=0x6B;//PWR_MGMT_1
	I2CWrite(addr, reg);
	I2CWrite(addr, 0x00);

	reg=0x3B;//ACCEL_XOUT_H
	I2CMultiByteRead(addr, reg, data, 14);
	accel_x = (data[0] << 8) | data[1];
	accel_y = (data[2] << 8) | data[3];
	accel_z = (data[4] << 8) | data[5];
	temp_raw = (data[6] << 8) | data[7];
	gyro_x = (data[8] << 8) | data[9];
	gyro_y = (data[10] << 8) | data[11];
	gyro_z = (data[12] << 8) | data[13];

	sprintf(str,"accel_x=%d, accel_y=%d, accel_z=%d\r\n",accel_x,accel_y,accel_z);
	UartPuts(str);
	sprintf(str,"gyro_x=%d, gyro_y=%d, gyro_z=%d\r\n",gyro_x,gyro_y,gyro_z);
	UartPuts(str);

	temp_mc=((int32_t)temp_raw*1000)/340+36530;
	temp_c=temp_mc/1000;
	sprintf(str,"Temperature in degrees C = %ld.%03ld\n",temp_c,temp_mc%1000);
	UartPuts(str);
}

